In [1]:
inputs = [1, 2, 3, 2.5]
weights = [3, 4, 5, -3]
bias = 3

output = inputs[0]*weights[0]+bias+inputs[1] * \
    weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]


In [2]:
output


21.5

In [4]:
inputs = [1, 2, 3, 2.5]

weights1 = [3, 4, 5, -3]
weights2 = [4, 5, 67, 8]
weights3 = [2.9, 6.7, 45, 70]

bias1 = 3
bias2 = 4
bias3 = 1

output = [inputs[0]*weights1[0]+bias1+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights[3],
          inputs[0]*weights2[0]+bias2+inputs[1]*weights2[1] +
          inputs[2]*weights2[2]+inputs[3]*weights[3],
          inputs[0]*weights3[0]+bias3+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights[3]]


In [5]:
output


[21.5, 211.5, 144.8]

In [6]:
weights = [[3, 4, 5, -3],
           [4, 5, 67, 8],
           [2.9, 6.7, 45, 70]]

biases = [3, 4, 1]

layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)


[21.5, 239.0, 327.3]


In [7]:
for i in weights:
    print(i)


[3, 4, 5, -3]
[4, 5, 67, 8]
[2.9, 6.7, 45, 70]


In [8]:
import numpy as np

inputs = [1, 2, 3, 2.5]
weights = [3, 4, 5, -3]
bias = 3

output = np.dot(inputs, weights)+bias


In [9]:
output


21.5

In [10]:
print(np.dot(weights, inputs)+bias)


21.5


In [11]:
weights = [[3, 4, 5, -3],
           [4, 5, 67, 8],
           [2.9, 6.7, 45, 70]]

biases = [3, 4, 1]

output = np.dot(weights, inputs)+bias
output


array([ 21.5, 238. , 329.3])

In [ ]:
print(np.dot(inputs, weights))

In [13]:
inputs = [[1, -2, 3, 4],
          [6, 0, -6, 5],
          [4, 5, -7, -22]]

weights = [[3, 4, 5, -3],
           [4, 5, 67, 8],
           [2.9, 6.7, 45, 70]]

biases = [3, 4, 1]


In [14]:
type(inputs)


list

In [15]:
output = np.dot(inputs, np.array(weights).T)+biases
output


array([[ 1.0000e+00,  2.3100e+02,  4.0550e+02],
       [-2.4000e+01, -3.3400e+02,  9.8400e+01],
       [ 6.6000e+01, -6.0000e+02, -1.8089e+03]])

In [16]:
np.random.seed(0)
X = [
    [1, 2, 3, 2.5],
    [3.0, 5.6, 6, 7],
    [4, 5, 6, 7]
]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons)
        self.biases = np.ones((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights)+self.biases


layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)


[[ 2.07581312 11.39835225  3.44624108  4.1821498   2.88510534]
 [ 4.01938263 26.70516132  6.21873209 10.06617804  5.5865348 ]
 [ 6.3698017  26.53526547  7.2882844  12.36900255  7.20773369]]


In [17]:
print(np.ones((3, 1)))


[[1.]
 [1.]
 [1.]]


In [18]:
layer2.forward(layer1.output)
print(layer2.output)


[[ 17.98933865  -7.65833907]
 [ 36.96199895 -18.91240591]
 [ 35.83247396 -16.85448646]]


In [19]:
print('hello,hope you are there')


hello,hope you are there


In [20]:
class Activation_Relu:
    def forward(self, input):
        self.output = np.maximum(0, input)


In [25]:
from nnfs.datasets import spiral_data
X, y = spiral_data(100, 3)

In [27]:
layer1 = Layer_Dense(2, 5)

activation = Activation_Relu()

layer1.forward(X)


In [28]:
activation.forward(layer1.output)
print(activation.output)


[[1.         1.         1.         1.         1.        ]
 [1.00802739 0.97956959 1.00659873 0.98995891 1.00837962]
 [1.00827682 0.97131311 1.00510299 0.99231241 1.0454176 ]
 ...
 [1.18000993 0.02950039 1.03363905 0.95402051 3.66025113]
 [0.11656082 2.63604559 0.13713407 2.31922215 3.03280776]
 [0.75020746 0.93364405 0.63798859 1.55799872 4.12717065]]


In [ ]:
layer_outputs = [[4.8, 1.21, 2.385],
                 [-1.2, 3.4, -5.6],
                 [3.4, 5.6, 2.1]]

exp_values = np.exp(layer_outputs)
norm_values = exp_values/np.sum(exp_values, axis=1, keepdims=True)
# print(np.sum(layer_outputs,axis=1,keepdims=True))

print(norm_values)